-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.587 sec <<< FAILURE! - in TestSuite
dummy_test_to_fail(Test.test)  Time elapsed: 0.019 sec  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [1]
	at Test.test.dummy_test_to_fail(test.java:16)

